### PR TITLE
Ic2 classic compat

### PR DESCRIPTION
**Pull request by Trinsdar**
It's  not complete so don't  merge yet.

### CODE REVIEW

**Comment by Trinsdar** [comment]
nevermind I might make ic2 classic specific compat in another branch and have it as a seperate version as the items seem too dependent on ic2 experimental and they have ic2 experimental features and texture style, not ic2 classic features and texture styles
plus that way I could also make the classic version have classic features and stuff and have classic texture styles

**Comment by Trinsdar** [comment]
that said I will still cleanup code on this branch and stuff.

**Comment by Trinsdar** [comment]
do note that you will have to run setupDecompWorkspace every time you switch branches

**Comment by Trinsdar** [comment]
although maybe there is a way to make it do ic2 classic style stuff when ic2 classic is loaded and ic2 experimental stuff when ic2 experimental is loaded, therefore having just one version. means though that the items would not be able to extend any ic2 core classes. they can still import from both though.

**Comment by Trinsdar** [comment]
the drills and such(if any don't already use the api) should be no problem. it's the armor that will be the major problem

**Comment by Trinsdar** [comment]
ok so scrap the idea I ha of using both core classes. the armor will have to use specifically api and forge methods only, no core methods with exceptions to a couple methods in IC2 core that are in both classic and experimental

**Comment by Trinsdar** [comment]
The main problem of using just the api is the jetpack logic and such will have to be written in the armor class as it would merely extend ItemChestplate(I think that's what the vanilla class is)

**Comment by Trinsdar** [comment]
~~Also do you have a discord?~~ Never mind I found it.

**Comment by Rumaruka** [comment]
https://discord.gg/hSgvnS

**Pull request merged**
